name: BestCasino
main: Coline\Casino\BestCasinoMain
author: Алексей
version: 2.0
api: [2.0.0, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: STARTUP
website: infomcpe.ru
commands:
    settingcasino:
        description: "Настройка казино"
