name: BestCasino
main: Coline\Casino\BestCasinoMain
author: ColineTeam
version: 2.1
api: [3.0.0-ALPHA12, 3.0.0]
load: STARTUP
website: pmine.ru
commands:
    settingcasino:
        description: "Настройка казино"
